"""initial schema: systems, evidence, catalogs, controls, validation results, findings, manifests

Revision ID: b297497b0925
Revises:
Create Date: 2026-01-08 16:28:17.230480

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b297497b0925"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "catalogs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("version", sa.String(length=50), nullable=True),
        sa.Column("framework", sa.String(length=100), nullable=False),
        sa.Column("baseline", sa.String(length=50), nullable=True),
        sa.Column("oscal_path", sa.String(length=500), nullable=True),
        sa.Column("loaded_at", sa.DateTime(), nullable=True),
        sa.Column("attributes", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_catalogs_framework"), "catalogs", ["framework"], unique=False)
    op.create_index(op.f("ix_catalogs_name"), "catalogs", ["name"], unique=True)
    op.create_table(
        "systems",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("environment", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("attributes", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_systems_created_at"), "systems", ["created_at"], unique=False)
    op.create_index(op.f("ix_systems_environment"), "systems", ["environment"], unique=False)
    op.create_index(op.f("ix_systems_name"), "systems", ["name"], unique=True)
    op.create_table(
        "controls",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("catalog_id", sa.Integer(), nullable=False),
        sa.Column("control_id", sa.String(length=50), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("family", sa.String(length=10), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("remediation", sa.Text(), nullable=True),
        sa.Column("baseline_required", sa.Boolean(), nullable=True),
        sa.Column("attributes", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["catalog_id"],
            ["catalogs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_controls_catalog_id"), "controls", ["catalog_id"], unique=False)
    op.create_index(op.f("ix_controls_control_id"), "controls", ["control_id"], unique=False)
    op.create_index(op.f("ix_controls_family"), "controls", ["family"], unique=False)
    op.create_table(
        "evidence",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("system_id", sa.Integer(), nullable=False),
        sa.Column("evidence_type", sa.String(length=100), nullable=False),
        sa.Column("key", sa.String(length=500), nullable=False),
        sa.Column("vault_path", sa.String(length=500), nullable=True),
        sa.Column("filename", sa.String(length=255), nullable=True),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("size", sa.Integer(), nullable=True),
        sa.Column("collected_at", sa.DateTime(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.Column("attributes", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["system_id"],
            ["systems.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_evidence_collected_at"), "evidence", ["collected_at"], unique=False)
    op.create_index(op.f("ix_evidence_evidence_type"), "evidence", ["evidence_type"], unique=False)
    op.create_index(op.f("ix_evidence_expires_at"), "evidence", ["expires_at"], unique=False)
    op.create_index(op.f("ix_evidence_sha256"), "evidence", ["sha256"], unique=False)
    op.create_index(op.f("ix_evidence_system_id"), "evidence", ["system_id"], unique=False)
    op.create_table(
        "evidence_manifests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("system_id", sa.Integer(), nullable=True),
        sa.Column("environment", sa.String(length=50), nullable=False),
        sa.Column("version", sa.String(length=10), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("overall_hash", sa.String(length=64), nullable=False),
        sa.Column("signed_by", sa.String(length=255), nullable=True),
        sa.Column("signature", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("attributes", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["system_id"],
            ["systems.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_evidence_manifests_created_at"), "evidence_manifests", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_evidence_manifests_system_id"), "evidence_manifests", ["system_id"], unique=False
    )
    op.create_table(
        "control_requirements",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("control_id", sa.Integer(), nullable=False),
        sa.Column("required_any", sa.JSON(), nullable=False),
        sa.Column("required_all", sa.JSON(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["control_id"],
            ["controls.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_control_requirements_control_id"),
        "control_requirements",
        ["control_id"],
        unique=False,
    )
    op.create_table(
        "evidence_manifest_entries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("manifest_id", sa.Integer(), nullable=False),
        sa.Column("evidence_id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(length=500), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("size", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["evidence_id"],
            ["evidence.id"],
        ),
        sa.ForeignKeyConstraint(
            ["manifest_id"],
            ["evidence_manifests.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_evidence_manifest_entries_evidence_id"),
        "evidence_manifest_entries",
        ["evidence_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_evidence_manifest_entries_manifest_id"),
        "evidence_manifest_entries",
        ["manifest_id"],
        unique=False,
    )
    op.create_table(
        "findings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("system_id", sa.Integer(), nullable=False),
        sa.Column("control_id", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("found_at", sa.DateTime(), nullable=False),
        sa.Column("closed_at", sa.DateTime(), nullable=True),
        sa.Column("attributes", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["control_id"],
            ["controls.id"],
        ),
        sa.ForeignKeyConstraint(
            ["system_id"],
            ["systems.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_findings_control_id"), "findings", ["control_id"], unique=False)
    op.create_index(op.f("ix_findings_found_at"), "findings", ["found_at"], unique=False)
    op.create_index(op.f("ix_findings_severity"), "findings", ["severity"], unique=False)
    op.create_index(op.f("ix_findings_status"), "findings", ["status"], unique=False)
    op.create_index(op.f("ix_findings_system_id"), "findings", ["system_id"], unique=False)
    op.create_table(
        "validation_results",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("system_id", sa.Integer(), nullable=False),
        sa.Column("control_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PASS", "FAIL", "INSUFFICIENT_EVIDENCE", "UNKNOWN", name="validationstatus"),
            nullable=False,
        ),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("evidence_keys", sa.JSON(), nullable=False),
        sa.Column("remediation", sa.Text(), nullable=True),
        sa.Column("validated_at", sa.DateTime(), nullable=False),
        sa.Column("attributes", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["control_id"],
            ["controls.id"],
        ),
        sa.ForeignKeyConstraint(
            ["system_id"],
            ["systems.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_validation_results_control_id"), "validation_results", ["control_id"], unique=False
    )
    op.create_index(
        op.f("ix_validation_results_status"), "validation_results", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_validation_results_system_id"), "validation_results", ["system_id"], unique=False
    )
    op.create_index(
        op.f("ix_validation_results_validated_at"),
        "validation_results",
        ["validated_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_validation_results_validated_at"), table_name="validation_results")
    op.drop_index(op.f("ix_validation_results_system_id"), table_name="validation_results")
    op.drop_index(op.f("ix_validation_results_status"), table_name="validation_results")
    op.drop_index(op.f("ix_validation_results_control_id"), table_name="validation_results")
    op.drop_table("validation_results")
    op.drop_index(op.f("ix_findings_system_id"), table_name="findings")
    op.drop_index(op.f("ix_findings_status"), table_name="findings")
    op.drop_index(op.f("ix_findings_severity"), table_name="findings")
    op.drop_index(op.f("ix_findings_found_at"), table_name="findings")
    op.drop_index(op.f("ix_findings_control_id"), table_name="findings")
    op.drop_table("findings")
    op.drop_index(
        op.f("ix_evidence_manifest_entries_manifest_id"), table_name="evidence_manifest_entries"
    )
    op.drop_index(
        op.f("ix_evidence_manifest_entries_evidence_id"), table_name="evidence_manifest_entries"
    )
    op.drop_table("evidence_manifest_entries")
    op.drop_index(op.f("ix_control_requirements_control_id"), table_name="control_requirements")
    op.drop_table("control_requirements")
    op.drop_index(op.f("ix_evidence_manifests_system_id"), table_name="evidence_manifests")
    op.drop_index(op.f("ix_evidence_manifests_created_at"), table_name="evidence_manifests")
    op.drop_table("evidence_manifests")
    op.drop_index(op.f("ix_evidence_system_id"), table_name="evidence")
    op.drop_index(op.f("ix_evidence_sha256"), table_name="evidence")
    op.drop_index(op.f("ix_evidence_expires_at"), table_name="evidence")
    op.drop_index(op.f("ix_evidence_evidence_type"), table_name="evidence")
    op.drop_index(op.f("ix_evidence_collected_at"), table_name="evidence")
    op.drop_table("evidence")
    op.drop_index(op.f("ix_controls_family"), table_name="controls")
    op.drop_index(op.f("ix_controls_control_id"), table_name="controls")
    op.drop_index(op.f("ix_controls_catalog_id"), table_name="controls")
    op.drop_table("controls")
    op.drop_index(op.f("ix_systems_name"), table_name="systems")
    op.drop_index(op.f("ix_systems_environment"), table_name="systems")
    op.drop_index(op.f("ix_systems_created_at"), table_name="systems")
    op.drop_table("systems")
    op.drop_index(op.f("ix_catalogs_name"), table_name="catalogs")
    op.drop_index(op.f("ix_catalogs_framework"), table_name="catalogs")
    op.drop_table("catalogs")
    # ### end Alembic commands ###
